"""Initial migration

Revision ID: 250177434a27
Revises:
Create Date: 2026-01-21 05:29:33.230007

"""

# revision identifiers, used by Alembic.
revision = "250177434a27"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
